spring.application.name=reactive-ai-streaming-service
server.port=8080

spring.ai.openai.base-url=https://openrouter.ai/api/v1
spring.ai.openai.api-key=${ROUTER_API_KEY:sk-or-v1-default-mock-key}
spring.ai.openai.chat.options.model=google/gemini-2.5-flash
